title: Streamdata Gallery AWS Identity and Access Management
url: aws-identity-and-access-management.streamdata.gallery
tag: AWS Identity and Access Management
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: aws-identity-and-access-management
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
